### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by timea-techgirl** [NVISO-BE/nexus_5_bootloader_unpacker#1]
Can you please upload binaries? I don't know how to.

**Comment by Cizzle** [comment]
How to compile the binaries is given in the readme. For the imgdata_tool you will also need the libpng header files. If you get errors during compilation, it would help if you could provide the full compilation output.

**Comment by timea-techgirl** [comment]
Well, I don't understand these things. I'm not into computers. :(

**Comment by Cizzle** [comment]
You will have to ask someone else then. You also haven't stated for which OS these binaries would be; if it is Windows then some alterations to the code are probably also necessary.

**Comment by timea-techgirl** [comment]
Windows 7 x64.

**Comment by timea-techgirl** [comment]
Thanks for your help. I don't know anyone else.
If some people who really need it and can't use your software, what's the point?
